"""knowledge graph + learner core

Revision ID: 0002_knowledge_core
Revises: 0001_enable_extensions
Create Date: 2026-06-30 11:36:08.539512

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002_knowledge_core"
down_revision: str | Sequence[str] | None = "0001_enable_extensions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learners",
        sa.Column("handle", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_learners_handle"), "learners", ["handle"], unique=True)
    op.create_table(
        "subjects",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subjects_slug"), "subjects", ["slug"], unique=True)
    op.create_table(
        "topics",
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_id", "slug"),
    )
    op.create_index(op.f("ix_topics_subject_id"), "topics", ["subject_id"], unique=False)
    op.create_table(
        "kcs",
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("topic_id", "slug"),
    )
    op.create_index(op.f("ix_kcs_topic_id"), "kcs", ["topic_id"], unique=False)
    op.create_table(
        "kc_edges",
        sa.Column("prereq_kc_id", sa.Uuid(), nullable=False),
        sa.Column("kc_id", sa.Uuid(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("prereq_kc_id <> kc_id", name="kc_edge_no_self_loop"),
        sa.ForeignKeyConstraint(["kc_id"], ["kcs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["prereq_kc_id"], ["kcs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prereq_kc_id", "kc_id"),
    )
    op.create_index(op.f("ix_kc_edges_kc_id"), "kc_edges", ["kc_id"], unique=False)
    op.create_index(op.f("ix_kc_edges_prereq_kc_id"), "kc_edges", ["prereq_kc_id"], unique=False)
    op.create_table(
        "learner_kc_state",
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("kc_id", sa.Uuid(), nullable=False),
        sa.Column("ability", sa.Float(), nullable=False),
        sa.Column("uncertainty", sa.Float(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["kc_id"], ["kcs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["learner_id"], ["learners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("learner_id", "kc_id"),
    )
    op.create_index(op.f("ix_learner_kc_state_kc_id"), "learner_kc_state", ["kc_id"], unique=False)
    op.create_index(
        op.f("ix_learner_kc_state_learner_id"), "learner_kc_state", ["learner_id"], unique=False
    )
    op.create_table(
        "learning_events",
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("kc_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["kc_id"], ["kcs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["learner_id"], ["learners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_events_created_at"), "learning_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_learning_events_event_type"), "learning_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_learning_events_kc_id"), "learning_events", ["kc_id"], unique=False)
    op.create_index(
        op.f("ix_learning_events_learner_id"), "learning_events", ["learner_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_learning_events_learner_id"), table_name="learning_events")
    op.drop_index(op.f("ix_learning_events_kc_id"), table_name="learning_events")
    op.drop_index(op.f("ix_learning_events_event_type"), table_name="learning_events")
    op.drop_index(op.f("ix_learning_events_created_at"), table_name="learning_events")
    op.drop_table("learning_events")
    op.drop_index(op.f("ix_learner_kc_state_learner_id"), table_name="learner_kc_state")
    op.drop_index(op.f("ix_learner_kc_state_kc_id"), table_name="learner_kc_state")
    op.drop_table("learner_kc_state")
    op.drop_index(op.f("ix_kc_edges_prereq_kc_id"), table_name="kc_edges")
    op.drop_index(op.f("ix_kc_edges_kc_id"), table_name="kc_edges")
    op.drop_table("kc_edges")
    op.drop_index(op.f("ix_kcs_topic_id"), table_name="kcs")
    op.drop_table("kcs")
    op.drop_index(op.f("ix_topics_subject_id"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_subjects_slug"), table_name="subjects")
    op.drop_table("subjects")
    op.drop_index(op.f("ix_learners_handle"), table_name="learners")
    op.drop_table("learners")
    # ### end Alembic commands ###
