/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subjects */
        get: operations["list_subjects_api_v1_subjects_get"];
        put?: never;
        /** Create Subject */
        post: operations["create_subject_api_v1_subjects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subject */
        get: operations["get_subject_api_v1_subjects__subject_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects/{subject_id}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["list_topics_api_v1_subjects__subject_id__topics_get"];
        put?: never;
        /** Create Topic */
        post: operations["create_topic_api_v1_subjects__subject_id__topics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{topic_id}/kcs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Kcs */
        get: operations["list_kcs_api_v1_topics__topic_id__kcs_get"];
        put?: never;
        /** Create Kc */
        post: operations["create_kc_api_v1_topics__topic_id__kcs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kcs/{kc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kc */
        get: operations["get_kc_api_v1_kcs__kc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kcs/{kc_id}/prerequisites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Prerequisite */
        post: operations["add_prerequisite_api_v1_kcs__kc_id__prerequisites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_v1_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_api_v1_conversations__conversation_id__messages_get"];
        put?: never;
        /**
         * Send Message
         * @description Persist the user turn, then stream the tutor's reply as Server-Sent Events.
         */
        post: operations["send_message_api_v1_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Item */
        post: operations["create_item_api_v1_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_api_v1_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Item */
        post: operations["answer_item_api_v1_items__item_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Due Reviews
         * @description KCs whose FSRS-scheduled review has come due, soonest first, each paired with an
         *     answerable flashcard where one was eagerly resolved (see ``session_runner.due_review_items``
         *     and the ``reviews_due_item_limit`` cost bound).
         */
        get: operations["due_reviews_api_v1_reviews_due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Source
         * @description Stream an upload to a temp file (size-capped), store it, and queue ingestion.
         *
         *     The file is streamed to disk in chunks so an arbitrarily large upload never sits in
         *     memory; it is rejected with 413 the moment it exceeds ``max_upload_bytes``.
         */
        post: operations["upload_source_api_v1_sources_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link Source
         * @description Register a web page for ingestion. The page is fetched in the background job.
         */
        post: operations["link_source_api_v1_sources_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["get_source_api_v1_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrieve Chunks
         * @description Hybrid-retrieve the most relevant chunks for a query, scoped to the learner.
         */
        post: operations["retrieve_chunks_api_v1_retrieve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source Chunks */
        get: operations["get_source_chunks_api_v1_sources__source_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Content
         * @description Generate a block of the given ``type`` (or assemble the default set) for a KC.
         *
         *     Cache-aware: an identical request reuses stored blocks rather than regenerating.
         */
        post: operations["generate_content_api_v1_content_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/kc/{kc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Kc Content
         * @description Read the cached content blocks for a KC, scoped to the learner (no generation).
         */
        get: operations["get_kc_content_api_v1_content_kc__kc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects/{subject_id}/placement/prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Placement Prompt */
        get: operations["get_placement_prompt_api_v1_subjects__subject_id__placement_prompt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects/{subject_id}/placement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Placement */
        post: operations["run_placement_api_v1_subjects__subject_id__placement_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Profile */
        post: operations["refresh_profile_api_v1_profile_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/{key}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Dimension */
        post: operations["reset_dimension_api_v1_profile__key__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects/{subject_id}/lesson-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lesson Plan */
        get: operations["get_lesson_plan_api_v1_subjects__subject_id__lesson_plan_get"];
        put?: never;
        /** Generate Lesson Plan */
        post: operations["generate_lesson_plan_api_v1_subjects__subject_id__lesson_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/memory/write-back": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write Back */
        post: operations["write_back_api_v1_conversations__conversation_id__memory_write_back_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memory */
        get: operations["list_memory_api_v1_memory_get"];
        put?: never;
        post?: never;
        /**
         * Delete All Memory
         * @description Erase every memory for the caller — the bulk "forget me" endpoint.
         */
        delete: operations["delete_all_memory_api_v1_memory_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Memory */
        delete: operations["delete_memory_api_v1_memory__memory_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Liveness check.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerSubmit
         * @description A learner's response. ``response`` shape depends on the item type (see grading).
         */
        AnswerSubmit: {
            /** Response */
            response: {
                [key: string]: unknown;
            };
            /** Latency Ms */
            latency_ms?: number | null;
            /** Hints Used */
            hints_used?: number | null;
        };
        /** Body_upload_source_api_v1_sources_upload_post */
        Body_upload_source_api_v1_sources_upload_post: {
            /** File */
            file: string;
            /** Subject Id */
            subject_id?: string | null;
            /** Topic Id */
            topic_id?: string | null;
        };
        /** ChatTurnRequest */
        ChatTurnRequest: {
            /** Content */
            content: string;
            /**
             * Satisfied
             * @default false
             */
            satisfied: boolean;
            /**
             * Mode
             * @default chat
             * @enum {string}
             */
            mode: "chat" | "agentic" | "workflow";
        };
        /**
         * ChunkRead
         * @description A stored chunk as exposed for debugging — text + provenance, not the raw vector.
         */
        ChunkRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ordinal */
            ordinal: number;
            /** Text */
            text: string;
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
        };
        /**
         * ContentBlockRead
         * @description A generated, KC-tagged content block with its grounding citations.
         */
        ContentBlockRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kc Ids */
            kc_ids: string[];
            /** Block Type */
            block_type: string;
            /** Body */
            body: string;
            /** Citations */
            citations: {
                [key: string]: unknown;
            }[];
            /** Model */
            model: string;
        };
        /**
         * ContentType
         * @description The kind of generated block; also selects the model tier that produces it.
         * @enum {string}
         */
        ContentType: "lesson" | "wiki_brief" | "wiki_full" | "question";
        /** ConversationCreate */
        ConversationCreate: {
            /** Title */
            title?: string | null;
            /** Subject Id */
            subject_id?: string | null;
        };
        /** ConversationRead */
        ConversationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Learner Id
             * Format: uuid
             */
            learner_id: string;
            /** Title */
            title: string | null;
            /** Goal */
            goal: string | null;
            /** Subject Id */
            subject_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DimensionRead */
        DimensionRead: {
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Source */
            source: string;
            /** Value */
            value: unknown;
            /** Uncertainty */
            uncertainty: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * GenerateRequest
         * @description Generate content for a KC. With ``type`` omitted, the default block set is assembled.
         */
        GenerateRequest: {
            /**
             * Kc Id
             * Format: uuid
             */
            kc_id: string;
            type?: components["schemas"]["ContentType"] | null;
        };
        /**
         * GradeRead
         * @description The grade plus the per-KC mastery the answer produced.
         */
        GradeRead: {
            /** Score */
            score: number;
            /** Correct */
            correct: boolean;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Estimates */
            estimates: components["schemas"]["KCEstimateRead"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemCreate */
        ItemCreate: {
            item_type: components["schemas"]["ItemType"];
            /** Stem */
            stem: string;
            /** Kcs */
            kcs: components["schemas"]["ItemKCRef"][];
            /** Answer Key */
            answer_key?: {
                [key: string]: unknown;
            } | null;
            /**
             * Difficulty
             * @default 0
             */
            difficulty: number;
            /** Rubric Id */
            rubric_id?: string | null;
        };
        /** ItemKCRead */
        ItemKCRead: {
            /**
             * Kc Id
             * Format: uuid
             */
            kc_id: string;
            /** Weight */
            weight: number;
        };
        /**
         * ItemKCRef
         * @description A KC this item assesses, with its apportioning weight.
         */
        ItemKCRef: {
            /**
             * Kc Id
             * Format: uuid
             */
            kc_id: string;
            /**
             * Weight
             * @default 1
             */
            weight: number;
        };
        /**
         * ItemRead
         * @description An item as presented to a learner — the ``answer_key`` is deliberately withheld.
         */
        ItemRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            item_type: components["schemas"]["ItemType"];
            /** Stem */
            stem: string;
            /** Difficulty */
            difficulty: number;
            /** Rubric Id */
            rubric_id: string | null;
            /** Kcs */
            kcs: components["schemas"]["ItemKCRead"][];
        };
        /**
         * ItemType
         * @description The kinds of assessment item. The first three grade deterministically.
         * @enum {string}
         */
        ItemType: "mcq" | "cloze" | "fill_blank" | "short" | "long" | "flashcard";
        /** KCCreate */
        KCCreate: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * KCDetail
         * @description A KC plus its inbound prerequisite edges.
         */
        KCDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /**
             * Prerequisites
             * @default []
             */
            prerequisites: components["schemas"]["PrerequisiteRead"][];
        };
        /** KCEstimateRead */
        KCEstimateRead: {
            /**
             * Kc Id
             * Format: uuid
             */
            kc_id: string;
            /** Ability */
            ability: number;
            /** Uncertainty */
            uncertainty: number;
        };
        /** KCRead */
        KCRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
        };
        /** LessonPlanRead */
        LessonPlanRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Goal */
            goal: string | null;
            /** Pacing */
            pacing: string;
            /** Example Tags */
            example_tags: string[];
            /** Reading Level Hint */
            reading_level_hint: number | null;
            /** Steps */
            steps: components["schemas"]["LessonStepRead"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LessonPlanSubmit */
        LessonPlanSubmit: {
            /** Goal */
            goal?: string | null;
        };
        /** LessonStepRead */
        LessonStepRead: {
            /**
             * Kc Id
             * Format: uuid
             */
            kc_id: string;
            /** Order */
            order: number;
            /** Step Type */
            step_type: string;
            /** Status */
            status: string;
            /** Target Difficulty */
            target_difficulty: number | null;
            /** Hint Density */
            hint_density: string | null;
            /** Preferred Item Type */
            preferred_item_type: string | null;
        };
        /**
         * LinkCreate
         * @description Request to ingest a public web page.
         */
        LinkCreate: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Subject Id */
            subject_id?: string | null;
            /** Topic Id */
            topic_id?: string | null;
        };
        /**
         * MemoryRead
         * @description A stored memory as exposed to the learner — not the raw embedding.
         */
        MemoryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Content */
            content: string;
            /** Conversation Id */
            conversation_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MessageRead */
        MessageRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Model */
            model: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PlacementPromptRead */
        PlacementPromptRead: {
            /** Question */
            question: string;
        };
        /** PlacementResultRead */
        PlacementResultRead: {
            /** Seeded */
            seeded: components["schemas"]["KCEstimateRead"][];
            /** Light Test Items */
            light_test_items: components["schemas"]["ItemRead"][];
        };
        /** PlacementSubmit */
        PlacementSubmit: {
            /** Background */
            background: string;
        };
        /**
         * PrerequisiteCreate
         * @description Declare that ``prereq_kc_id`` is a prerequisite of the KC in the path.
         */
        PrerequisiteCreate: {
            /**
             * Prereq Kc Id
             * Format: uuid
             */
            prereq_kc_id: string;
            /**
             * Weight
             * @default 1
             */
            weight: number;
        };
        /** PrerequisiteRead */
        PrerequisiteRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Prereq Kc Id
             * Format: uuid
             */
            prereq_kc_id: string;
            /**
             * Kc Id
             * Format: uuid
             */
            kc_id: string;
            /** Weight */
            weight: number;
        };
        /** ProfileSnapshotRead */
        ProfileSnapshotRead: {
            /** Dimensions */
            dimensions: components["schemas"]["DimensionRead"][];
        };
        /**
         * RetrievalHit
         * @description A retrieved chunk with its fused score and provenance.
         */
        RetrievalHit: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Text */
            text: string;
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
            /** Score */
            score: number;
        };
        /**
         * RetrieveRequest
         * @description A hybrid-retrieval query, optionally scoped to a subject/topic/source.
         */
        RetrieveRequest: {
            /** Query */
            query: string;
            /** Subject Id */
            subject_id?: string | null;
            /** Topic Id */
            topic_id?: string | null;
            /** Source Id */
            source_id?: string | null;
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /**
         * ReviewItemRead
         * @description A KC whose FSRS review is due (the review-queue projection).
         *
         *     ``item`` is an answerable practice item resolved for the KC (typically a flashcard —
         *     see ``session_runner.due_review_items``), or ``None`` past the request's item-resolution
         *     cap (``reviews_due_item_limit``) — the due list itself is bounded separately (much more
         *     generously, see ``mastery.due_reviews``'s ``due_reviews_limit``), only item resolution
         *     beyond ``reviews_due_item_limit`` is skipped.
         */
        ReviewItemRead: {
            /**
             * Kc Id
             * Format: uuid
             */
            kc_id: string;
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            /** Ability */
            ability: number;
            /** Uncertainty */
            uncertainty: number;
            item?: components["schemas"]["ItemRead"] | null;
        };
        /**
         * SourceRead
         * @description An ingestion source and its current status.
         */
        SourceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Origin */
            origin: string;
            /** Content Type */
            content_type: string | null;
            /** Status */
            status: string;
            /** Error */
            error: string | null;
            /** Subject Id */
            subject_id: string | null;
            /** Topic Id */
            topic_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SubjectCreate */
        SubjectCreate: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** SubjectRead */
        SubjectRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
        };
        /** TopicCreate */
        TopicCreate: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** TopicRead */
        TopicRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WriteBackAck
         * @description Acknowledges a queued write-back job — the created memories aren't returned
         *     synchronously; see ``GET /memory`` once the job has run.
         */
        WriteBackAck: {
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_subjects_api_v1_subjects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"][];
                };
            };
        };
    };
    create_subject_api_v1_subjects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subject_api_v1_subjects__subject_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topics_api_v1_subjects__subject_id__topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_topic_api_v1_subjects__subject_id__topics_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_kcs_api_v1_topics__topic_id__kcs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KCRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_kc_api_v1_topics__topic_id__kcs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KCCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KCRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kc_api_v1_kcs__kc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KCDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_prerequisite_api_v1_kcs__kc_id__prerequisites_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrerequisiteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrerequisiteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_v1_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRead"][];
                };
            };
        };
    };
    create_conversation_api_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_v1_conversations__conversation_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_v1_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_v1_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_v1_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_item_api_v1_items__item_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    due_reviews_api_v1_reviews_due_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemRead"][];
                };
            };
        };
    };
    upload_source_api_v1_sources_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_source_api_v1_sources_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_source_api_v1_sources_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_v1_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_chunks_api_v1_retrieve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrieveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_chunks_api_v1_sources__source_id__chunks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_content_api_v1_content_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentBlockRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kc_content_api_v1_content_kc__kc_id__get: {
        parameters: {
            query?: {
                type?: components["schemas"]["ContentType"] | null;
            };
            header?: never;
            path: {
                kc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentBlockRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_placement_prompt_api_v1_subjects__subject_id__placement_prompt_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementPromptRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_placement_api_v1_subjects__subject_id__placement_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlacementSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementResultRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSnapshotRead"];
                };
            };
        };
    };
    refresh_profile_api_v1_profile_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSnapshotRead"];
                };
            };
        };
    };
    reset_dimension_api_v1_profile__key__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_plan_api_v1_subjects__subject_id__lesson_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonPlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_lesson_plan_api_v1_subjects__subject_id__lesson_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonPlanSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonPlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_back_api_v1_conversations__conversation_id__memory_write_back_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteBackAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memory_api_v1_memory_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_all_memory_api_v1_memory_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_memory_api_v1_memory__memory_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
